### ISSUE TITLE
Disappear css includes after refresh page

### ISSUE THREAD

**Issue by skutylev** [applegrew/django-select2#203] opened 2015-09-20 19:51 UTC
Im using django-select2 with django-suit. In admin page, dissapear css lines after refresh page
<link href="/static/django_select2/css/select2.css" type="text/css" media="screen" rel="stylesheet" /><link href="/static/django_select2/css/extra.css" type="text/css" media="screen" rel="stylesheet" />
<img width="858" alt="2015-09-20 22 31 31" src="https://cloud.githubusercontent.com/assets/9027455/9982548/d0c98376-5fe8-11e5-9414-36c903950c8a.png">
<img width="1064" alt="2015-09-20 22 31 44" src="https://cloud.githubusercontent.com/assets/9027455/9982547/d0c82ca6-5fe8-11e5-86c3-1ae620fdc0c5.png">

**Comment by narrowfail** [comment] 2015-09-22 04:03
Same problem over here. Started yesterday. Any idea?

**Comment by skutylev** [comment] 2015-09-22 08:48
I have included this string in base.html in django-suit. But I think this is temporary solution.

**Comment by narrowfail** [comment] 2015-09-22 19:40
Which one?

**Comment by skutylev** [comment] 2015-09-22 19:50
i have added 
<link href="/static/django_select2/css/select2.css" type="text/css" media="screen" rel="stylesheet" />
<link href="/static/django_select2/css/extra.css" type="text/css" media="screen" rel="stylesheet" />

in suit/templates/admin/base.html, but i think it is bad solution. 
In russian that named as spike :)

**Comment by codingjoe** [comment] 2015-09-23 08:55
@narrowfail what do you mean by "started yesterday"? We didn't release anything.

**Comment by narrowfail** [comment] 2015-09-23 22:39
Well, I did a deploy (collectstatic + apache restart). After that, the CSS was lost.
I had to use the tag "import_django_select2_js_css" in my base template.
I checked if AUTO_RENDER_SELECT2_STATICS was False, but it was on True.
The JS is loading without using the tag. The problem is just on the CSS.

**Comment by codingjoe** [comment] 2015-09-24 10:43
hm... good thing all that is removed in version 5. I won't fix this issue in version 4. If you want it fixed, you'll need to provide your own PR.

**Comment by narrowfail** [comment] 2015-09-24 18:13
But do you know why it failed from one day to another?

**Comment by codingjoe** [comment] 2015-09-29 13:54
Fixed in v5.

**Closed by codingjoe** 2015-09-29 13:54 UTC
Labels: bug, wontfix
